apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: etos-suite-starter
    literals:
      - SUITE_RUNNER=registry.nordix.org/eiffel/etos-suite-runner:f209b74c
      - LOG_LISTENER=registry.nordix.org/eiffel/etos-log-listener:f209b74c
  - name: etos-suite-runner
    literals:
      - ETR_VERSION="3.4.0"
